global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: encroach
    static_configs:
      - targets: ["host.docker.internal:3000"]
    metrics_path: /metrics
